// CODE GENERATED BY JAVADUDE BEAN ANNOTATION PROCESSOR 
// -- DO NOT EDIT  -  THIS CODE WILL BE REGENERATED! --
package sample;

@javax.annotation.Generated(
    value = "com.javadude.annotation.processors.BeanAnnotationProcessor", 
    date = "Wed Sep 23 15:34:02 EDT 2015", 
    comments = "CODE GENERATED BY JAVADUDE BEAN ANNOTATION PROCESSOR; DO NOT EDIT! THIS CODE WILL BE REGENERATED!")
public abstract class PersonGen  {
    public PersonGen() {
        ;
    }

    private java.lang.String name_;
    public java.lang.String getName() {
        return name_;
    }
    public void setName(java.lang.String value)  {
        name_ = value;
    }

    private java.lang.String address_;
    public java.lang.String getAddress() {
        return address_;
    }
    public void setAddress(java.lang.String value)  {
        address_ = value;
    }

    private java.lang.String phone_;
    public java.lang.String getPhone() {
        return phone_;
    }
    public void setPhone(java.lang.String value)  {
        phone_ = value;
    }


    @Override
    public java.lang.String toString() {
        return getClass().getName() + '[' + paramString() + ']';
    }
    protected java.lang.String paramString() {
        return 
               "name=" + name_ +
               ",address=" + address_ +
               ",phone=" + phone_;
    }
}
