// CODE GENERATED BY JAVADUDE BEAN ANNOTATION PROCESSOR 
// -- DO NOT EDIT  -  THIS CODE WILL BE REGENERATED! --
package com.javadude.annotation.processors;

@javax.annotation.Generated(
    value = "com.javadude.annotation.processors.BeanAnnotationProcessor", 
    date = "Wed Sep 23 15:34:02 EDT 2015", 
    comments = "CODE GENERATED BY JAVADUDE BEAN ANNOTATION PROCESSOR; DO NOT EDIT! THIS CODE WILL BE REGENERATED!")
public abstract class ListenerGen  {
    public ListenerGen() {
        ;
    }

    private java.lang.String name_;
    public java.lang.String getName() {
        return name_;
    }
    public void setName(java.lang.String value)  {
        name_ = value;
    }

    private java.lang.String lowerName_;
    public java.lang.String getLowerName() {
        return lowerName_;
    }
    public void setLowerName(java.lang.String value)  {
        lowerName_ = value;
    }

    private boolean overriding_;
    public boolean isOverriding() {
        return overriding_;
    }
    public void setOverriding(boolean value)  {
        overriding_ = value;
    }


    @Override
    public java.lang.String toString() {
        return getClass().getName() + '[' + paramString() + ']';
    }
    protected java.lang.String paramString() {
        return 
               "name=" + name_ +
               ",lowerName=" + lowerName_ +
               ",overriding=" + overriding_;
    }
}
