// CODE GENERATED BY JAVADUDE BEAN ANNOTATION PROCESSOR 
// -- DO NOT EDIT  -  THIS CODE WILL BE REGENERATED! --
package sample;

@javax.annotation.Generated(
    value = "com.javadude.annotation.processors.BeanAnnotationProcessor", 
    date = "Sun May 10 13:01:16 EDT 2009", 
    comments = "CODE GENERATED BY JAVADUDE BEAN ANNOTATION PROCESSOR; DO NOT EDIT! THIS CODE WILL BE REGENERATED!")
public abstract class DefaultParameterExampleGen  {
    public DefaultParameterExampleGen() {
        ;
    }


    protected void process(sample.Processor processor, java.lang.String item)  {
        process(processor, item, Processor.Size.LARGE, "red", 1);
    }
    protected void process(sample.Processor processor, java.lang.String item, sample.Processor.Size size)  {
        process(processor, item, size, "red", 1);
    }
    protected void process(sample.Processor processor, java.lang.String item, sample.Processor.Size size, java.lang.String color)  {
        process(processor, item, size, color, 1);
    }
    protected abstract void process(sample.Processor processor, java.lang.String item, sample.Processor.Size size, java.lang.String color, int quantity) ;
    public void report()  {
        report("Hello");
    }
    public abstract void report(java.lang.String message) ;
    @Override
    public java.lang.String toString() {
        return getClass().getName() + '[' + paramString() + ']';
    }
    protected java.lang.String paramString() {
        return "";
    }
}
